default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 54321
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: translate_words_development
test:
  <<: *default
  database: translate_words_test

production:
  <<: *default
  database: translate_words_production
  password: <%= ENV["TRANSLATE_WORDS_DATABASE_PASSWORD"] %>
